version: '3.3'
services:
  build:
    build: 
      context: ./build
    volumes:
      - type: volume
        source: wardir
        target: /home/user/target

#  prod:
#    build: 
#      context: ./prod
#    ports:
#      - "8080:8080"      

volumes:
  wardir:
#    - driver: local
