version: '3.3'
services:
  sbuild:
    build: 
      context: ./build
    volumes:
      - type: volume
        source: wardir
        target: /home/user/target

  sprod:
    build: 
      context: ./prod
    ports:
      - "8080:8080"      
    volumes:
      - type: volume
        source: wardir
        target: /usr/local/tomcat/webapps

volumes:
  wardir:
#    - driver: local
